### ISSUE TITLE
As a user I want to have a UI menu to navigate around

### ISSUE THREAD

**Issue by simonfrayer** [XRD10/x-wing-vr#22]
## Sub-issues
- [ ] Implemnt open/close UI menu
- [ ] Implement continue button
- [ ] Implement quit button
